#!/usr/bin/env bash
set -euo pipefail

NGROK_API_URL="http://127.0.0.1:4040/api/tunnels"
WEBHOOK_PATH="/webhook"
ENV_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ngrok-api-url)
      NGROK_API_URL="$2"
      shift 2
      ;;
    --webhook-path)
      WEBHOOK_PATH="$2"
      shift 2
      ;;
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$WEBHOOK_PATH" ]]; then
  WEBHOOK_PATH="/webhook"
fi
if [[ "$WEBHOOK_PATH" != /* ]]; then
  WEBHOOK_PATH="/$WEBHOOK_PATH"
fi

NGROK_BASE_URL="$(
  curl -sf "$NGROK_API_URL" | python3 - <<'PY'
import json
import sys

try:
    data = json.load(sys.stdin)
except Exception:
    raise SystemExit(1)

for tunnel in data.get("tunnels", []):
    url = str(tunnel.get("public_url") or "").strip()
    if url.startswith("https://"):
        print(url.rstrip("/"))
        raise SystemExit(0)
raise SystemExit(1)
PY
)" || {
  cat >&2 <<'EOF'
Unable to resolve an HTTPS ngrok tunnel.
Start ngrok first: ngrok http 8001
Then rerun: ./scripts/export_research_webhook_url.sh
EOF
  exit 1
}

RESEARCH_WEBHOOK_URL="${NGROK_BASE_URL}${WEBHOOK_PATH}"

if [[ "$RESEARCH_WEBHOOK_URL" != https://* ]]; then
  echo "Resolved webhook URL is not HTTPS: $RESEARCH_WEBHOOK_URL" >&2
  exit 1
fi

if [[ -n "$ENV_FILE" ]]; then
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    echo "# Generated by scripts/export_research_webhook_url.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "export NEXRA_RESEARCH_WEBHOOK_URL=\"$RESEARCH_WEBHOOK_URL\""
  } > "$ENV_FILE"
  echo "Wrote export command to $ENV_FILE"
fi

echo "export NEXRA_RESEARCH_WEBHOOK_URL=\"$RESEARCH_WEBHOOK_URL\""
echo "NEXRA_RESEARCH_WEBHOOK_URL is HTTPS and ready for demo/research_agent.py"
